spring.application.name=ngc-backend

supabase.url=https://vkandgvzpxpyvijwwaaj.supabase.co/rest/v1/
supabase.key=sb_publishable_657f3Z1zxNcI_hAOr64mcA_LCaeCrWl
supabase.schema=public

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect